# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/end_rom/end_rom.xci
# IP: The module: 'end_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/end_rom/end_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'end_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/end_rom/end_rom.xci
# IP: The module: 'end_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/end_rom/end_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'end_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
