# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Documents/Nexys4DDR_Master.xdc

# IP: ip/timer_rom/timer_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_rom || ORIG_REF_NAME==timer_rom} -quiet] -quiet

# IP: ip/timerframe_rom/timerframe_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timerframe_rom || ORIG_REF_NAME==timerframe_rom} -quiet] -quiet
