# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.cache/wt} [current_project]
set_property parent.project_path {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/charis.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/banner.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/castle_wall.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/target.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/cannon_45.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/cannon_30.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/cannon_60.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/cannonball.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/pwr.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/timer.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/timerframe.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/start.coe}}
add_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/sprites/end.coe}}
read_mem {
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/letter_f.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/palette.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/f_colour.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/image_quantizer/img_palette.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/image_quantizer/img.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/image_quantizer/banner_palette.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/image_quantizer/banner.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/wall_palette.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/target_palette.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/cannon_palette.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/cannonball_palette.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/pwr_palette.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/timerframe_palette.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/timer_palette.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/start_left.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/end_palette.mem}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/sprites/start_palette.mem}
}
read_verilog -library xil_defaultlib {
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/7segcode/seginterface.v}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/imports/7segcode/sevenseg.v}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/new/vga_timing.v}
  {C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/new/vga_out.v}
}
read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/timer_rom/timer_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/timer_rom/timer_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/timerframe_rom/timerframe_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/timerframe_rom/timerframe_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/banner_rom/banner_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/banner_rom/banner_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/wall_rom/wall_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/wall_rom/wall_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/target_rom/target_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/target_rom/target_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/cannon_45_rom/cannon_45_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/cannon_45_rom/cannon_45_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/cannon_30_rom/cannon_30_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/cannon_30_rom/cannon_30_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/cannon_60_rom/cannon_60_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/cannon_60_rom/cannon_60_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/cannonball_rom/cannonball_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/cannonball_rom/cannonball_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/pwr_rom/pwr_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/pwr_rom/pwr_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/start_rom/start_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/start_rom/start_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/end_rom/end_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/sources_1/ip/end_rom/end_rom_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/constrs_1/imports/Documents/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/u2012758/OneDrive - University of Warwick/Work/es2e3/coursework/vga_output/vga_output.srcs/constrs_1/imports/Documents/Nexys4DDR_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top vga_out -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_out.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vga_out_utilization_synth.rpt -pb vga_out_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
